spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: classpath:application-db.yml
  jpa:
    open-in-view: false

jobrunr:
  database:
    type: sql
  background-job-server:
    enabled: true
    thread-type: VirtualThreads
    worker-count: ${JOBRUNR_WORKER_COUNT:8}
  dashboard:
    enabled: false
