-- Initial domain schema (PostgreSQL 16). Master data is seeded by a separate migration.
-- Instants use timestamptz; business dates stay date. The application supplies timestamps.
-- Visible character limits are validated by VisibleLength, not SQL code-point counts.

CREATE TABLE emotion_characters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL CONSTRAINT ux_emotion_characters_code UNIQUE,
    name text NOT NULL CONSTRAINT ux_emotion_characters_name UNIQUE,
    display_order int NOT NULL,
    active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_emotion_characters_code CHECK (code IN ('anger', 'neutral', 'happiness', 'sadness', 'surprise', 'embarrassment', 'stress'))
);

CREATE TABLE situation_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CONSTRAINT ux_situation_types_name UNIQUE,
    onboarding_selectable boolean NOT NULL,
    before_selectable boolean NOT NULL,
    display_order int NOT NULL,
    active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE body_symptoms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CONSTRAINT ux_body_symptoms_name UNIQUE,
    description text,
    symptom_type text NOT NULL,
    onboarding_selectable boolean NOT NULL,
    after_selectable boolean NOT NULL,
    display_order int NOT NULL,
    active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_body_symptoms_symptom_type CHECK (symptom_type IN ('physical', 'behavioral', 'other'))
);

CREATE TABLE distortion_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CONSTRAINT ux_distortion_tags_name UNIQUE,
    definition text NOT NULL,
    example_thoughts jsonb NOT NULL,
    self_questions jsonb NOT NULL,
    reframes jsonb NOT NULL,
    display_order int NOT NULL,
    theme_color text,
    illustration_key text,
    active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_distortion_tags_example_thoughts CHECK (jsonb_typeof(example_thoughts) = 'array' AND NOT jsonb_path_exists(example_thoughts, '$[*] ? (@.type() != "string")')),
    CONSTRAINT ck_distortion_tags_self_questions CHECK (jsonb_typeof(self_questions) = 'array' AND NOT jsonb_path_exists(self_questions, '$[*] ? (@.type() != "string")')),
    CONSTRAINT ck_distortion_tags_reframes CHECK (jsonb_typeof(reframes) = 'array' AND NOT jsonb_path_exists(reframes, '$[*] ? (@.type() != "string")'))
);

CREATE TABLE positive_solutions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    situation_type_id bigint,
    category_code text NOT NULL,
    category_name text NOT NULL,
    title text NOT NULL,
    solution_content text NOT NULL,
    active boolean NOT NULL,
    display_order int NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_positive_solutions_situation_type_id FOREIGN KEY (situation_type_id) REFERENCES situation_types (id) ON DELETE RESTRICT,
    CONSTRAINT ck_positive_solutions_category_code CHECK (category_code IN ('awareness', 'evidence_check', 'reframing', 'body_regulation', 'resilience'))
);

CREATE TABLE anxiety_patterns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL CONSTRAINT ux_anxiety_patterns_code UNIQUE,
    name text NOT NULL,
    description text,
    active boolean NOT NULL,
    display_order int NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    password_hash text,
    password_changed_at timestamptz,
    email_verified_at timestamptz,
    failed_login_count int NOT NULL DEFAULT 0,
    failed_login_window_started_at timestamptz,
    login_locked_until timestamptz,
    nickname text NOT NULL,
    representative_character_id bigint NOT NULL,
    current_emotion_code text,
    gender text,
    birth_year int,
    onboarding_completed boolean NOT NULL DEFAULT false,
    onboarding_completed_at timestamptz,
    data_generation bigint NOT NULL DEFAULT 0,
    account_status text NOT NULL,
    baseline_discomfort_score int,
    notification_time time,
    after_reminder_enabled boolean NOT NULL,
    weekly_report_start_day text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_users_representative_character_id FOREIGN KEY (representative_character_id) REFERENCES emotion_characters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_users_current_emotion_code FOREIGN KEY (current_emotion_code) REFERENCES emotion_characters (code) ON DELETE RESTRICT,
    CONSTRAINT ck_users_gender CHECK (gender IN ('female', 'male')),
    CONSTRAINT ck_users_account_status CHECK (account_status IN ('onboarding', 'active', 'deleting')),
    CONSTRAINT ck_users_weekly_report_start_day CHECK (weekly_report_start_day IN ('sun', 'mon')),
    CONSTRAINT ck_users_email_trimmed CHECK (email = btrim(email) AND email <> ''),
    CONSTRAINT ck_users_failed_login_count CHECK (failed_login_count >= 0),
    CONSTRAINT ck_users_data_generation CHECK (data_generation >= 0),
    CONSTRAINT ck_users_baseline_score CHECK (baseline_discomfort_score BETWEEN 0 AND 100)
);

CREATE TABLE social_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    provider text NOT NULL,
    provider_uid text NOT NULL,
    connected_at timestamptz NOT NULL,
    CONSTRAINT fk_social_accounts_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_social_accounts_provider CHECK (provider IN ('google')),
    CONSTRAINT ux_social_accounts_provider_uid UNIQUE (provider, provider_uid)
);

CREATE TABLE user_agreements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    agreement_type text NOT NULL,
    agreement_version text NOT NULL,
    agreed boolean NOT NULL,
    agreed_at timestamptz NOT NULL,
    CONSTRAINT fk_user_agreements_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_agreements_agreement_type CHECK (agreement_type IN ('terms', 'privacy', 'sensitive', 'marketing'))
);

CREATE TABLE before_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    situation_type_id bigint NOT NULL,
    title text,
    description text,
    scheduled_at date NOT NULL,
    expected_score int NOT NULL,
    expected_score_comment text,
    worst_scenario text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_before_logs_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_before_logs_situation_type_id FOREIGN KEY (situation_type_id) REFERENCES situation_types (id) ON DELETE RESTRICT,
    CONSTRAINT ck_before_logs_expected_score CHECK (expected_score BETWEEN 0 AND 100)
);

CREATE TABLE after_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    before_log_id bigint NOT NULL,
    actual_score int,
    actual_score_comment text,
    free_writing text NOT NULL,
    final_diary text,
    record_status text NOT NULL,
    input_version bigint NOT NULL DEFAULT 1,
    finalized_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_after_logs_before_log_id FOREIGN KEY (before_log_id) REFERENCES before_logs (id) ON DELETE CASCADE,
    CONSTRAINT ck_after_logs_record_status CHECK (record_status IN ('DRAFT', 'FINALIZED')),
    CONSTRAINT ux_after_logs_before_log_id UNIQUE (before_log_id),
    CONSTRAINT ck_after_logs_actual_score CHECK (actual_score BETWEEN 0 AND 100),
    CONSTRAINT ck_after_logs_input_version CHECK (input_version >= 1),
    CONSTRAINT ck_after_logs_finalization CHECK (
        (record_status = 'DRAFT' AND actual_score IS NULL AND final_diary IS NULL AND finalized_at IS NULL)
        OR (record_status = 'FINALIZED' AND actual_score IS NOT NULL AND final_diary IS NOT NULL AND finalized_at IS NOT NULL)
    )
);

CREATE TABLE bf_ai_feedbacks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    before_log_id bigint NOT NULL,
    feedback_content text NOT NULL,
    similar_records_comment text,
    similar_record_ids jsonb,
    model_version text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_bf_ai_feedbacks_before_log_id FOREIGN KEY (before_log_id) REFERENCES before_logs (id) ON DELETE CASCADE,
    CONSTRAINT ux_bf_ai_feedbacks_before_log_id UNIQUE (before_log_id),
    CONSTRAINT ck_bf_ai_feedbacks_similar_records CHECK (CASE WHEN jsonb_typeof(similar_record_ids) = 'array' THEN jsonb_array_length(similar_record_ids) <= 5 ELSE similar_record_ids IS NULL END)
);

CREATE TABLE af_ai_feedbacks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    after_log_id bigint NOT NULL,
    analysis_status text NOT NULL,
    input_version bigint NOT NULL,
    summary text,
    model_version text,
    input_snapshot json,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_af_ai_feedbacks_after_log_id FOREIGN KEY (after_log_id) REFERENCES after_logs (id) ON DELETE CASCADE,
    CONSTRAINT ck_af_ai_feedbacks_analysis_status CHECK (analysis_status IN ('NOT_REQUESTED', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'INVALIDATED')),
    CONSTRAINT ux_af_ai_feedbacks_after_log_id UNIQUE (after_log_id),
    CONSTRAINT ck_af_ai_feedbacks_input_version CHECK (input_version >= 1)
);

CREATE TABLE ai_insights (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    after_log_id bigint NOT NULL,
    insight_type text NOT NULL,
    display_order int NOT NULL,
    insight_content text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_ai_insights_after_log_id FOREIGN KEY (after_log_id) REFERENCES after_logs (id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_insights_insight_type CHECK (insight_type IN ('record_comparison', 'situation_pattern', 'reflection_question', 'external_factor', 'factor_feedback', 'coping_suggestion')),
    CONSTRAINT ux_ai_insights_id_after_log UNIQUE (id, after_log_id)
);

CREATE TABLE user_insights (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    insight_type text NOT NULL,
    situation_type_id bigint,
    period_start date,
    period_end date,
    content jsonb NOT NULL,
    model_version text NOT NULL,
    computed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_user_insights_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_insights_situation_type_id FOREIGN KEY (situation_type_id) REFERENCES situation_types (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_insights_insight_type CHECK (insight_type IN ('growth', 'situation_comparison', 'distortion_stats')),
    CONSTRAINT ux_user_insights_scope UNIQUE NULLS NOT DISTINCT (user_id, insight_type, period_start, period_end, situation_type_id),
    CONSTRAINT ck_user_insights_situation CHECK ((insight_type = 'situation_comparison' AND situation_type_id IS NOT NULL) OR (insight_type <> 'situation_comparison' AND situation_type_id IS NULL)),
    CONSTRAINT ck_user_insights_period CHECK (period_start <= period_end)
);

CREATE TABLE after_symptoms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    after_log_id bigint NOT NULL,
    body_symptom_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_after_symptoms_after_log_id FOREIGN KEY (after_log_id) REFERENCES after_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_after_symptoms_body_symptom_id FOREIGN KEY (body_symptom_id) REFERENCES body_symptoms (id) ON DELETE RESTRICT,
    CONSTRAINT ux_after_symptoms_pair UNIQUE (after_log_id, body_symptom_id)
);

CREATE TABLE after_distortions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    after_log_id bigint NOT NULL,
    distortion_tag_id bigint NOT NULL,
    evidence text NOT NULL,
    explanation text NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_after_distortions_after_log_id FOREIGN KEY (after_log_id) REFERENCES after_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_after_distortions_distortion_tag_id FOREIGN KEY (distortion_tag_id) REFERENCES distortion_tags (id) ON DELETE RESTRICT
);

CREATE TABLE after_analysis_cards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    after_log_id bigint NOT NULL,
    input_version bigint NOT NULL,
    distortion_tag_id bigint,
    tag_label text NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    display_order int NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_after_analysis_cards_after_log_id FOREIGN KEY (after_log_id) REFERENCES after_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_after_analysis_cards_distortion_tag_id FOREIGN KEY (distortion_tag_id) REFERENCES distortion_tags (id) ON DELETE RESTRICT,
    CONSTRAINT ck_after_analysis_cards_input_version CHECK (input_version >= 1)
);

CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    type text NOT NULL,
    priority int NOT NULL,
    before_log_id bigint,
    trigger_keyword text,
    trigger_at date,
    scheduled_at timestamptz NOT NULL,
    dedup_key text NOT NULL,
    status text NOT NULL,
    dismissed_at timestamptz,
    read_at timestamptz,
    last_shown_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_before_log_id FOREIGN KEY (before_log_id) REFERENCES before_logs (id) ON DELETE CASCADE,
    CONSTRAINT ck_notifications_type CHECK (type IN ('before_induce', 'after_induce')),
    CONSTRAINT ck_notifications_status CHECK (status IN ('pending', 'shown', 'dismissed', 'cancelled')),
    CONSTRAINT ck_notifications_trigger_keyword CHECK (trigger_keyword IN ('발표', '시험', '면접')),
    CONSTRAINT ux_notifications_user_dedup UNIQUE (user_id, dedup_key),
    CONSTRAINT ck_notifications_target CHECK ((type = 'before_induce' AND before_log_id IS NULL) OR (type = 'after_induce' AND before_log_id IS NOT NULL))
);

CREATE TABLE device_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    token text NOT NULL CONSTRAINT ux_device_tokens_token UNIQUE,
    platform text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_device_tokens_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_device_tokens_platform CHECK (platform IN ('ios', 'android', 'web'))
);

CREATE TABLE refresh_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    device_token_id bigint,
    refresh_token_hash text NOT NULL CONSTRAINT ux_refresh_sessions_refresh_token_hash UNIQUE,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_refresh_sessions_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_sessions_device_token_id FOREIGN KEY (device_token_id) REFERENCES device_tokens (id) ON DELETE SET NULL
);

CREATE TABLE user_notification_states (
    user_id bigint PRIMARY KEY,
    suppressed_until timestamptz,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_user_notification_states_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE notification_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id bigint NOT NULL,
    device_token_id bigint,
    channel text NOT NULL,
    status text NOT NULL,
    sent_at timestamptz,
    failure_code text,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_notification_deliveries_notification_id FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_deliveries_device_token_id FOREIGN KEY (device_token_id) REFERENCES device_tokens (id) ON DELETE SET NULL,
    CONSTRAINT ck_notification_deliveries_channel CHECK (channel IN ('push')),
    CONSTRAINT ck_notification_deliveries_status CHECK (status IN ('pending', 'processing', 'sent', 'failed', 'cancelled'))
);

CREATE TABLE user_onboarding_situations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    situation_type_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_user_onboarding_situations_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_onboarding_situations_situation_type_id FOREIGN KEY (situation_type_id) REFERENCES situation_types (id) ON DELETE RESTRICT,
    CONSTRAINT ux_user_onboarding_situations_pair UNIQUE (user_id, situation_type_id)
);

CREATE TABLE user_onboarding_symptoms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    body_symptom_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_user_onboarding_symptoms_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_onboarding_symptoms_body_symptom_id FOREIGN KEY (body_symptom_id) REFERENCES body_symptoms (id) ON DELETE RESTRICT,
    CONSTRAINT ux_user_onboarding_symptoms_pair UNIQUE (user_id, body_symptom_id)
);

CREATE TABLE user_anxiety_patterns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    anxiety_pattern_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_user_anxiety_patterns_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_anxiety_patterns_anxiety_pattern_id FOREIGN KEY (anxiety_pattern_id) REFERENCES anxiety_patterns (id) ON DELETE RESTRICT,
    CONSTRAINT ux_user_anxiety_patterns_pair UNIQUE (user_id, anxiety_pattern_id)
);

CREATE TABLE after_factor_judgements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    after_log_id bigint NOT NULL,
    ai_insight_id bigint NOT NULL CONSTRAINT ux_after_factor_judgements_ai_insight_id UNIQUE,
    answer boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_after_factor_judgements_after_log_id FOREIGN KEY (after_log_id) REFERENCES after_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_after_factor_judgements_insight_after FOREIGN KEY (ai_insight_id, after_log_id) REFERENCES ai_insights (id, after_log_id) ON DELETE CASCADE
);

CREATE TABLE ai_jobs (
    id uuid PRIMARY KEY,
    user_id bigint NOT NULL,
    before_log_id bigint,
    after_log_id bigint,
    kind text NOT NULL,
    status text NOT NULL,
    request_key uuid NOT NULL,
    input_version bigint NOT NULL,
    data_generation bigint NOT NULL,
    input_snapshot jsonb NOT NULL,
    result jsonb,
    failure_reason text,
    retryable boolean NOT NULL,
    expires_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_ai_jobs_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_jobs_before_log_id FOREIGN KEY (before_log_id) REFERENCES before_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_jobs_after_log_id FOREIGN KEY (after_log_id) REFERENCES after_logs (id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_jobs_kind CHECK (kind IN ('before_rebuttal', 'after_analysis', 'diary_draft', 'record_insight')),
    CONSTRAINT ck_ai_jobs_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ux_ai_jobs_request UNIQUE (user_id, kind, request_key),
    CONSTRAINT ck_ai_jobs_input_version CHECK (input_version >= 1),
    CONSTRAINT ck_ai_jobs_data_generation CHECK (data_generation >= 0),
    CONSTRAINT ck_ai_jobs_target CHECK ((kind = 'before_rebuttal' AND after_log_id IS NULL) OR (kind <> 'before_rebuttal' AND after_log_id IS NOT NULL AND before_log_id IS NULL))
);

CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));
CREATE UNIQUE INDEX ux_ai_jobs_active_after_kind ON ai_jobs (after_log_id, kind)
    WHERE status IN ('PENDING', 'PROCESSING');
CREATE INDEX ix_notifications_unread ON notifications (user_id) WHERE read_at IS NULL;
CREATE INDEX ix_users_representative_character_id ON users (representative_character_id);
CREATE INDEX ix_users_current_emotion_code ON users (current_emotion_code);
CREATE INDEX ix_social_accounts_user_id ON social_accounts (user_id);
CREATE INDEX ix_user_agreements_user_id ON user_agreements (user_id);
CREATE INDEX ix_before_logs_user_id ON before_logs (user_id);
CREATE INDEX ix_before_logs_situation_type_id ON before_logs (situation_type_id);
CREATE INDEX ix_ai_insights_after_log_id ON ai_insights (after_log_id);
CREATE INDEX ix_user_insights_situation_type_id ON user_insights (situation_type_id);
CREATE INDEX ix_after_symptoms_body_symptom_id ON after_symptoms (body_symptom_id);
CREATE INDEX ix_after_distortions_after_log_id ON after_distortions (after_log_id);
CREATE INDEX ix_after_distortions_distortion_tag_id ON after_distortions (distortion_tag_id);
CREATE INDEX ix_after_analysis_cards_after_log_id ON after_analysis_cards (after_log_id);
CREATE INDEX ix_after_analysis_cards_distortion_tag_id ON after_analysis_cards (distortion_tag_id);
CREATE INDEX ix_positive_solutions_situation_type_id ON positive_solutions (situation_type_id);
CREATE INDEX ix_notifications_before_log_id ON notifications (before_log_id);
CREATE INDEX ix_device_tokens_user_id ON device_tokens (user_id);
CREATE INDEX ix_refresh_sessions_user_id ON refresh_sessions (user_id);
CREATE INDEX ix_refresh_sessions_device_token_id ON refresh_sessions (device_token_id);
CREATE INDEX ix_notification_deliveries_notification_id ON notification_deliveries (notification_id);
CREATE INDEX ix_notification_deliveries_device_token_id ON notification_deliveries (device_token_id);
CREATE INDEX ix_user_onboarding_situations_situation_type_id ON user_onboarding_situations (situation_type_id);
CREATE INDEX ix_user_onboarding_symptoms_body_symptom_id ON user_onboarding_symptoms (body_symptom_id);
CREATE INDEX ix_user_anxiety_patterns_anxiety_pattern_id ON user_anxiety_patterns (anxiety_pattern_id);
CREATE INDEX ix_after_factor_judgements_after_log_id ON after_factor_judgements (after_log_id);
CREATE INDEX ix_ai_jobs_before_log_id ON ai_jobs (before_log_id);
CREATE INDEX ix_ai_jobs_after_log_id ON ai_jobs (after_log_id);
